name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  CHART_NAME: "statefulset-app"

jobs:
  build:
    name: Build
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{github.event.pull_request.head.sha}}

    # Set Up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.8.2

    # Lint
    - name: Helm Lint
      run: |
        helm lint ${CHART_NAME}

    # Dry run to ensure that manifests are generated successfully
    - name: Dry Run Chart
      run: |
        helm template ${CHART_NAME} ${CHART_NAME} -n test-namespace --dry-run --debug

  # check-helm-docs: # The readme generation is currently broken
  #   name: Check Helm Docs
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         ref: ${{github.event.pull_request.head.sha}}
  #     - name: Run helm-docs
  #       uses: losisin/helm-docs-github-action@6bf14d5bdb7346c5876b2b3ea96bfb8f0f53c556 # v1.3.4
  #       with:
  #         # Keep args in sync with /.pre-commit-config.yaml
  #         output-file: README.md
  #         template-files: README.md.gotmpl
  #         sort-values-order: file
  #         chart-search-root: .
  #     - name: Check diff
  #       run: |
  #         git diff --exit-code README.md || { echo; echo "error: README.md is out of date. Please run `make build-docs` and commit the resulting file."; exit 1; }
