name: Push

concurrency:
 group: push_on_main
 cancel-in-progress: false

on:
  push:
    branches:
      - main
    paths-ignore:
    - 'README.md'

env:
  CHART_NAME: "statefulset-app"

jobs:
  push-changes:
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo

    # Generate tag for chart without "v" prefix
    - name: Generate Tag
      id: generate_tag
      uses: anothrNick/github-tag-action@1.71.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
        DRY_RUN: true

    # Update chart tag to the latest semver tag
    - name: Update Chart Version
      env:
        VERSION: ${{ steps.generate_tag.outputs.new_tag }}
      run: |
        make bump-chart

    # Set Up Helm
    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: v3.8.2

    # Publish helm chart to GitHub Pages
    - name: Publish Helm chart
      uses: stefanprodan/helm-gh-pages@v1.7.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        charts_dir: .
        target_dir: charts

    # Commit back changes
    - name: Commit files
      run: |
        git status
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add ${CHART_NAME}/Chart.yaml
        git commit -m "[skip-ci] Update chart version to ${{ steps.generate_tag.outputs.new_tag }}"

    # Push Chart.yaml with Updated Version
    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main

    # Push Latest Tag
    - name: Push Latest Tag
      uses: anothrNick/github-tag-action@1.71.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
